apiVersion: v1
kind: Service
metadata:
  name: calendar-api-service
  namespace: calendar-app
spec:
  selector:
    app: calendar-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80