version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-calendar}
      POSTGRES_USER: ${POSTGRES_USER:-calendar_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-calendar}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      timeout: 5s
      retries: 30
      start_period: 80s
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data:delegated