version: "3.9"

services:
  api:
    build:
      context: ../
      dockerfile: ./deployments/images/api/Dockerfile    
    depends_on:
      db:
        condition: service_healthy
    ports: 
      - 8080:8080
    links: 
      - db

  scheduler:
    build:
      context: ../
      dockerfile: ./deployments/images/scheduler/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy        
      db:
        condition: service_healthy        
    links: 
      - db
      - rabbitmq

  sender:
    build:
      context: ../
      dockerfile: ./deployments/images/sender/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy        
    links:
      - rabbitmq

  db:
    build:
      context: ../
      dockerfile: ./deployments/images/postgres/Dockerfile    
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "calendar" ]
      timeout: 5s
      retries: 30
      start_period: 80s
    ports:
      - 5432:5432    
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data:delegated
  
  rabbitmq:
    image:  rabbitmq:3-management
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - 15672:15672
      - 5672:5672    