[logger]
level = "DEBUG"

[storage]
type = "inmemory"

[postgres]
dsn = "postgres://calendar:calendar@localhost:5432/calendar"

[grpc]
host = "localhost"
port = 50051

[http]
host = "localhost"
port = 8080
timeout = 30
