[logger]
level = "DEBUG"

[storage]
type = "postgres"

[postgres]
dsn = "postgres://calendar:calendar@localhost:5432/calendar"

[grpc]
host = "localhost"
port = 50051

[http]
host = "localhost"
port = 8080
timeout = 30

[scheduler]
eventsNotifyCheckFrequency = "1m"
oldEventsCleanerFrequency="1h"

[rabbit]
uri = "amqp://guest:guest@localhost:5672"
exchange = "calendar-notify-exchange"
queue = "calendar-notify-queue"

